# Generated by Django 5.1.7 on 2025-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('other', 'Other')], max_length=20)),
                ('input_text', models.TextField(help_text="User's input description for metadata generation")),
                ('video_url', models.URLField(blank=True, help_text='Optional URL to the video', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Metadata Generation',
                'verbose_name_plural': 'Metadata Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('other', 'Other')], max_length=20)),
                ('title_format', models.CharField(blank=True, help_text='Format for titles with placeholders', max_length=255)),
                ('description_format', models.TextField(blank=True, help_text='Format for descriptions with placeholders')),
                ('tags_template', models.JSONField(blank=True, default=list, help_text='Common tags to include')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metadata Template',
                'verbose_name_plural': 'Metadata Templates',
                'ordering': ['name'],
            },
        ),
    ]
